module.exports.authController = require('./auth.controller')
module.exports.categoryController = require('./category.controller')
module.exports.orderController = require('./order.controller')
module.exports.partnerController = require('./partner.controller')
module.exports.productController = require('./product.controller')
module.exports.tableController = require('./table.controller')
module.exports.userController = require('./user.controller')